apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-sql
  namespace: devopschallenge
data:
  01_create_messages.sql: |
    CREATE TABLE IF NOT EXISTS messages(
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      message TEXT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
