# postgres-configmap.yml (data bölümüne ekle veya güncelle)
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-sql
  namespace: devopschallenge
data:
  00_init.sql: |
    DO $$ BEGIN
      CREATE ROLE emine LOGIN PASSWORD 'emine';
    EXCEPTION WHEN duplicate_object THEN
      RAISE NOTICE 'role emine already exists';
    END $$;

    -- Database 'mydb' is created by the official entrypoint when POSTGRES_DB is set.
    -- Avoid CREATE DATABASE inside a transaction (forbidden by PostgreSQL) to prevent init errors.
    -- If you ever need conditional DB creation in SQL, prefer psql's \gexec approach in a script run outside a DO block.

  01_create_messages.sql: |
    CREATE TABLE IF NOT EXISTS messages(
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      text TEXT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
