apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devopschallenge
  labels:
    app: postgres
type: Opaque
stringData:
  user: emine
  password: super-secure-pass
  db: mydb
