apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devopschallenge
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: __POSTGRES_USERNAME__
  POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
  POSTGRES_DB: __POSTGRES_DB__
