apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devopschallenge
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: emine
  POSTGRES_PASSWORD: emine
  POSTGRES_DB: mydb
