# postgres-configmap.yml (data bölümüne ekle veya güncelle)
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-sql
  namespace: devopschallenge
data:
  00_init.sql: |
    DO $$ BEGIN
      CREATE ROLE emine LOGIN PASSWORD 'emine';
    EXCEPTION WHEN duplicate_object THEN
      RAISE NOTICE 'role emine already exists';
    END $$;

    -- Idempotent DB creation without transaction block (works in psql)
    SELECT 'CREATE DATABASE mydb OWNER emine'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mydb')\gexec

  01_create_messages.sql: |
    \connect mydb
    -- Create/own table as app user to avoid permission issues
    SET ROLE emine;
    CREATE TABLE IF NOT EXISTS messages(
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      text TEXT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
    RESET ROLE;

    -- Ensure ownership and grants for existing clusters
    ALTER TABLE IF EXISTS messages OWNER TO emine;
    ALTER SEQUENCE IF EXISTS messages_id_seq OWNER TO emine;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE messages TO emine;
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE messages_id_seq TO emine;
